# Docker Compose configuration file for running the FastAPI service and the Telegram bot
networks:
  app: # main network
    # driver: host

volumes:
  app_db:

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mounts the current directory to /app in the container for hot reload
    environment:
      - API_PORT=8000
    networks:
      - app
    depends_on:
      - pdf_generator_service

  pdf_generator_service:
    build: ./services/pdf_generator
    container_name: pdf_generator_service
    ports:
      - "8001:8001"
    networks:
      - app


  song_generator:
    build: ./services/song_generator
    container_name: song_generator_service
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "8003:8003"
    volumes:
      - ./data:/data
    networks:
      - app