networks:
  app: # main network

volumes:
  app_db:
  ollama:

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api_service
    ports:
      - "8000:8000"
    volumes:
      - .:/api 
    environment:
      - API_PORT=8000
    networks:
      - app
    depends_on:
      - pdf_generator_service

  pdf_generator_service:
    build: ./services/pdf_generator
    container_name: pdf_generator_service
    ports:
      - "8001:8001"
    volumes:
      - ./services/pdf_generator:/app  # Bind mount for hot reload
    networks:
      - app

  song_generator_service:
    build: ./services/song_generator
    container_name: song_generator_service
    ports:
      - "8002:8002"
    volumes:
      - ./services/song_generator:/app  # Bind mount for hot reload
    networks:
      - app

  ollama:
    image: ollama/ollama:latest
    container_name: ollama_service
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    networks:
      - app
    healthcheck:
      test: ["CMD", "ollama", "--version"]
      interval: 30s
      timeout: 10s
      retries: 5